### ISSUE TITLE
Celery tasks

### ISSUE THREAD

**Issue by zqyves** [uber-common/metta#15]
hi guys, 

Thanks for releasing a great tool!!

Can I please ask if there were any design reasons you went for the 3 celery tasks, one for each platform, instead of having one and distinguishing there were to route the request ? It appears that most of the code in celery tasks `vagranttasks.py` and on the` run_uuid `method ( `if rule_os == "windows":` ...) is the same. Just wondering. 

Cheers

**Comment by carnal0wnage** [comment]
sorry for the late reply.  If it understand the question correctly...the thinking was 

there are different vagrant calls for vagrant wirm (windows) and vagrant ssh(osx/linux) - I'm sure it could be more eloquent i just split them out because they were initially written at different times.

that was probably an unclear answer to "no, no specific design decision aside from i was just muddling through doing things with celery".

If you have a better way to do it that would be awesome, do a branch and let's check out a  better way to do this.

CG

**Comment by carnal0wnage** [comment]
gonna close this. reopen if you want to continue the dialogue.
